### PR TITLE
ShaclGroup07

### PR DESCRIPTION
**Pull request by francesco-mattioli**

### CODE REVIEW

**Comment by rgcmme** [comment]
Fix the issues detected by the validation report.

**Comment by francesco-mattioli** [comment]
But we need to fix also the warnings? I saw on the forum that we don't need to fix them, isn' it?

**Comment by rgcmme** [comment]
That's correct. I don't know why I thought that there were other issues also.
You don't have to change anything.

**Comment by francesco-mattioli** [comment]
Perfect, no problem. Thank you!

**Pull request merged**
