### PR TITLE
Assignment4

### PR DESCRIPTION
**Pull request by LucaBestagno**

### CODE REVIEW

**Comment by anaigmo** [comment]
The uploaded files do not follow the guidelines provided in class: upload .py, not the notebook, and follow the notation for the folder

**Comment by LucaBestagno** [comment]
Good evening Professor, sorry for the late answer. I should have corrected the problem. Thank you for having let me know.

**Comment by dgarijo** [comment]
You are adding notebooks, not python scripts. Please follow the instructions shown in class

**Comment by LucaBestagno** [comment]
Sorry Professor, I checked the instructions showed in classed and corrected my mistakes.

**Comment by dgarijo** [comment]
You are removing the contents from the course materials. Only add things in your folder.

**Comment by dgarijo** [comment]
Now you are adding notebooks...have a look at the files changed tab

**Pull request closed without merging**
